### PR TITLE
Made a text proposal for E2E security

### PR DESCRIPTION
**Pull request by OliverPfaff**
Made a text proposal to have an anchor and starting point for the consideration of "E2E security", issue#144

***
<a href="https://pr-preview.s3.amazonaws.com/OliverPfaff/wot-security/pull/159.html" title="Last updated on Jan 30, 2020, 11:27 AM UTC (8616108)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/159/1858b19...OliverPfaff:8616108.html" title="Last updated on Jan 30, 2020, 11:27 AM UTC (8616108)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
It would be good if you could move the content to 
https://raw.githubusercontent.com/w3c/wot-security/master/index.html#sec-pract-end-to-end-security and strengthen that section, rather than creating a new section

**Comment by OliverPfaff** [comment]
Addressed this in PR#164

Apart from the end to refine the consideration around E2E security there are seems a need to add a new top-level section called "Security Considerations" - for reasons of consistency:
- The document headline is "Web of Things (WoT) Security and Privacy Guidelines" 
- The current text body has a headline 1 subsection "Privacy Considerations"
- There is not yet a headline 1 subsection "Security Considerations". The average reader should be expected to look for such a section. 

This is not yet covered by PR#164 and appears to remain as an open issue

**Comment by mmccool** [comment]
Is this PR now obsolete, given the PR https://github.com/w3c/wot-security/pull/164 ?   Should we close this PR without merging (note that a closed PR can be re-opened later if necessary...)?

**Comment by mmccool** [comment]
Agreed on March 23 security TF call to close without merging.

**Pull request closed without merging**
